spring:
  application:
    name  : store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update # Changed from 'create' to 'update' for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    lifecycle:
      timeout-per-shutdown-phase: 500s
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true


  lifecycle:
    timeout-per-shutdown-phase: 500s

stripe:
  apiUrl : https://api.stripe.com/
  enabled : true
  timeout :  1000
  supported-currencies : USD, EUR, GBP

payment-gateway: stripe

email:
  host: https://smtp.gmail.com
  port:   5761
